apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-git-generator
  namespace: argocd 
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - git:
      repoURL: https://github.com/ericmolinam/argocd-lab-apps.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/ericmolinam/argocd-lab-apps.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true